### PR TITLE
TG-456; Changed Logging from Errors to Warnings

### PR DESCRIPTION
**Pull request by reinhartfimqs**

### CODE REVIEW

**Comment by theunissens** [comment]
LGTM

**Comment by bmharper** [comment]
@reinhartfimqs @theunissens  What's the justification for changing all of these to warnings? It seems to me like some of them ought to remain as errors, eg "Unable to broadcast change, unable to read identities"

**Comment by reinhartfimqs** [comment]
That is what I was uncertain about, if you can point out which should remain as Error then I will change them back
The information contained in this communication from the sender is confidential. It is intended solely for use by the recipient and others authorized to receive it. If you are not the recipient, you are hereby notified that any disclosure, copying, distribution or taking action in relation of the contents of this information is strictly prohibited and may be unlawful. Please notify the sender by replying to this message and then delete it from your system. Please report email abuse / misuse to IMQS Software<www.imqs.co.za>.

**Comment by bmharper** [comment]
@reinhartfimqs Well.. *I* don't know! What's the root cause? What errors were occurring, with what frequency, and why? I assume devops has these answers for us.

**Comment by reinhartfimqs** [comment]
I will talk to DevOps and find out which ones was giving them problems and amend the changes accordingly.
The information contained in this communication from the sender is confidential. It is intended solely for use by the recipient and others authorized to receive it. If you are not the recipient, you are hereby notified that any disclosure, copying, distribution or taking action in relation of the contents of this information is strictly prohibited and may be unlawful. Please notify the sender by replying to this message and then delete it from your system. Please report email abuse / misuse to IMQS Software<www.imqs.co.za>.

**Pull request merged**
